// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/crypto_watch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CryptoWatchClient is the client API for CryptoWatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoWatchClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type cryptoWatchClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoWatchClient(cc grpc.ClientConnInterface) CryptoWatchClient {
	return &cryptoWatchClient{cc}
}

func (c *cryptoWatchClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/pb.CryptoWatch/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoWatchServer is the server API for CryptoWatch service.
// All implementations must embed UnimplementedCryptoWatchServer
// for forward compatibility
type CryptoWatchServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	mustEmbedUnimplementedCryptoWatchServer()
}

// UnimplementedCryptoWatchServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoWatchServer struct {
}

func (UnimplementedCryptoWatchServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedCryptoWatchServer) mustEmbedUnimplementedCryptoWatchServer() {}

// UnsafeCryptoWatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoWatchServer will
// result in compilation errors.
type UnsafeCryptoWatchServer interface {
	mustEmbedUnimplementedCryptoWatchServer()
}

func RegisterCryptoWatchServer(s grpc.ServiceRegistrar, srv CryptoWatchServer) {
	s.RegisterService(&CryptoWatch_ServiceDesc, srv)
}

func _CryptoWatch_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoWatchServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CryptoWatch/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoWatchServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoWatch_ServiceDesc is the grpc.ServiceDesc for CryptoWatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoWatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CryptoWatch",
	HandlerType: (*CryptoWatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _CryptoWatch_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crypto_watch.proto",
}
